-- Enable the btree_gist extension for advanced indexing
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Table for service types
CREATE TABLE service_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    duration_minutes INT NOT NULL,
    price_cents INT NOT NULL,
    deposit_cents INT,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Table for service zones
CREATE TABLE zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('zip_list', 'radius')),
    zip_codes TEXT[],
    center_lat DOUBLE PRECISION,
    center_lng DOUBLE PRECISION,
    radius_miles INT,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Table for assigning zones to specific dates
CREATE TABLE zone_day_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date" DATE NOT NULL UNIQUE,
    zone_id BIGINT REFERENCES zones(id),
    working_start_time TIME,
    working_end_time TIME,
    is_closed BOOLEAN DEFAULT FALSE NOT NULL,
    allow_mixed BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enum for booking status
CREATE TYPE booking_status AS ENUM ('HOLD', 'CONFIRMED', 'CANCELLED', 'EXPIRED');

-- Table for bookings
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    service_type_id BIGINT REFERENCES service_types(id) NOT NULL,
    zone_id BIGINT REFERENCES zones(id),
    address TEXT NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status booking_status NOT NULL,
    stripe_session_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    -- Constraint to prevent overlapping bookings that are either held or confirmed
    EXCLUDE USING GIST (
        tstzrange(start_time, end_time) WITH &&
    ) WHERE (status IN ('HOLD', 'CONFIRMED'))
);

-- Table for administrative blocks (e.g., vacations, lunch breaks)
CREATE TABLE blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    -- Constraint to prevent overlapping blocks
    EXCLUDE USING GIST (
        tstzrange(start_time, end_time) WITH &&
    )
);

-- Table for out-of-zone booking requests
CREATE TABLE booking_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    address TEXT NOT NULL,
    service_details TEXT,
    status TEXT DEFAULT 'pending' NOT NULL, -- e.g., pending, contacted, closed
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Function to automatically expire booking holds
CREATE OR REPLACE FUNCTION expire_old_holds()
RETURNS VOID AS $$
BEGIN
    UPDATE bookings
    SET status = 'EXPIRED'
    WHERE status = 'HOLD' AND created_at < NOW() - INTERVAL '10 minutes';
END;
$$ LANGUAGE plpgsql;
-- supabase/migrations/0003_admin_security.sql

-- Helper function to check for a custom 'admin' claim on the authenticated user.
create or replace function is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select coalesce(
    (auth.jwt() -> 'user_metadata' ->> 'is_admin')::boolean,
    false
  );
$$;
-- Enable RLS for all tables
ALTER TABLE "service_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "zones" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "zone_day_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bookings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "blocks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "booking_requests" ENABLE ROW LEVEL SECURITY;

-- Policies for service_types
-- Allow public read access for active services
CREATE POLICY "Allow public read access to active services" ON "service_types"
AS PERMISSIVE FOR SELECT
TO public
USING (active = true);

-- Allow admin full access
CREATE POLICY "Allow admin full access on service_types" ON "service_types"
FOR ALL
TO authenticated
USING (is_admin());

-- Policies for zones
-- Allow public read access for active zones
CREATE POLICY "Allow public read access to active zones" ON "zones"
AS PERMISSIVE FOR SELECT
TO public
USING (active = true);

-- Allow admin full access
CREATE POLICY "Allow admin full access on zones" ON "zones"
FOR ALL
TO authenticated
USING (is_admin());

-- Policies for zone_day_assignments
-- Allow public read access
CREATE POLICY "Allow public read access on zone_day_assignments" ON "zone_day_assignments"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- Allow admin full access
CREATE POLICY "Allow admin full access on zone_day_assignments" ON "zone_day_assignments"
FOR ALL
TO authenticated
USING (is_admin());

-- Policies for bookings
-- Deny all access to bookings from public
CREATE POLICY "Deny all access to bookings" ON "bookings"
AS RESTRICTIVE FOR ALL
TO public
USING (false);

-- Allow admin full access
CREATE POLICY "Allow admin full access on bookings" ON "bookings"
FOR ALL
TO authenticated
USING (is_admin());

-- Policies for blocks
-- Deny all access to blocks from public
CREATE POLICY "Deny all access to blocks" ON "blocks"
AS RESTRICTIVE FOR ALL
TO public
USING (false);

-- Allow admin full access
CREATE POLICY "Allow admin full access on blocks" ON "blocks"
FOR ALL
TO authenticated
USING (is_admin());

-- Policies for booking_requests
-- Allow public to create booking requests
CREATE POLICY "Allow public to create booking requests" ON "booking_requests"
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);

-- Deny public read access
CREATE POLICY "Deny public read access on booking_requests" ON "booking_requests"
AS RESTRICTIVE FOR SELECT
TO public
USING (false);

-- Allow admin full access
CREATE POLICY "Allow admin full access on booking_requests" ON "booking_requests"
FOR ALL
TO authenticated
USING (is_admin());
-- This script is safe to run multiple times.

-- Create a sample service (if it doesn't exist)
INSERT INTO service_types (id, name, description, duration_minutes, price_cents, active)
VALUES
  (2, 'Diagnostics', 'Full system diagnostic to identify any issues with your vehicle.', 60, 10000, true),
  (3, 'Full Synthetic Oil Change', 'Includes up to 2 quarts of full synthetic oil and a new oil filter.', 45, 8000, true),
  (4, 'Full Service', 'Includes oil/filter, air filter, carb clean, coolant flush, front and rear differential fluid, brake fluid, cable lube, chain clean, grease fittings flushed and filled, spark plugs, diagnostics and inspection.', 180, 48000, true),
  (5, 'Top-End Rebuild', 'Complete top-end engine rebuild with new piston, rings, and gaskets.', 240, 32000, true),
  (6, 'Low-End / Transmission Rebuild', 'Complete low-end and transmission inspection and rebuild.', 480, 64000, true)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  duration_minutes = EXCLUDED.duration_minutes,
  price_cents = EXCLUDED.price_cents,
  active = EXCLUDED.active;

-- Create a sample zone for Austin, TX (if it doesn't exist)
INSERT INTO zones (id, name, type, zip_codes, active)
VALUES (1, 'Austin Metro', 'zip_list', ARRAY['78701', '78702', '78703', '78704', '78705'], true)
ON CONFLICT (id) DO NOTHING;

-- Assign the 'Austin Metro' zone to tomorrow's date
-- This uses a bit of SQL magic to always use tomorrow's date for the assignment.
INSERT INTO zone_day_assignments (date, zone_id, working_start_time, working_end_time, is_closed, allow_mixed)
VALUES (current_date + interval '1 day', 1, '09:00:00', '17:00:00', false, false)
ON CONFLICT (date) DO UPDATE SET
  zone_id = 1,
  working_start_time = '09:00:00',
  working_end_time = '17:00:00',
  is_closed = false,
  allow_mixed = false;
