-- Enable the btree_gist extension for advanced indexing
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Table for service types
CREATE TABLE service_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    duration_minutes INT NOT NULL,
    price_cents INT NOT NULL,
    deposit_cents INT,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Table for service zones
CREATE TABLE zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('zip_list', 'radius')),
    zip_codes TEXT[],
    center_lat DOUBLE PRECISION,
    center_lng DOUBLE PRECISION,
    radius_miles INT,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Table for assigning zones to specific dates
CREATE TABLE zone_day_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date" DATE NOT NULL UNIQUE,
    zone_id BIGINT REFERENCES zones(id),
    working_start_time TIME,
    working_end_time TIME,
    is_closed BOOLEAN DEFAULT FALSE NOT NULL,
    allow_mixed BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enum for booking status
CREATE TYPE booking_status AS ENUM ('HOLD', 'CONFIRMED', 'CANCELLED', 'EXPIRED');

-- Table for bookings
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    service_type_id BIGINT REFERENCES service_types(id) NOT NULL,
    zone_id BIGINT REFERENCES zones(id),
    address TEXT NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status booking_status NOT NULL,
    stripe_session_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    -- Constraint to prevent overlapping bookings that are either held or confirmed
    EXCLUDE USING GIST (
        tstzrange(start_time, end_time) WITH &&
    ) WHERE (status IN ('HOLD', 'CONFIRMED'))
);

-- Table for administrative blocks (e.g., vacations, lunch breaks)
CREATE TABLE blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    -- Constraint to prevent overlapping blocks
    EXCLUDE USING GIST (
        tstzrange(start_time, end_time) WITH &&
    )
);

-- Table for out-of-zone booking requests
CREATE TABLE booking_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    address TEXT NOT NULL,
    service_details TEXT,
    status TEXT DEFAULT 'pending' NOT NULL, -- e.g., pending, contacted, closed
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Function to automatically expire booking holds
CREATE OR REPLACE FUNCTION expire_old_holds()
RETURNS VOID AS $$
BEGIN
    UPDATE bookings
    SET status = 'EXPIRED'
    WHERE status = 'HOLD' AND created_at < NOW() - INTERVAL '10 minutes';
END;
$$ LANGUAGE plpgsql;
